name: Magento Community Edition Docker container build
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cfg:
          - { PHP_VERSION: php7-fpm, MAGENTO_VERSION: 2.0.18, SAMPLE_DATA: false }
          - { PHP_VERSION: php7-fpm, MAGENTO_VERSION: 2.0.18, SAMPLE_DATA: true }
          - { PHP_VERSION: php7-fpm, MAGENTO_VERSION: 2.1.18, SAMPLE_DATA: false }
          - { PHP_VERSION: php7-fpm, MAGENTO_VERSION: 2.1.18, SAMPLE_DATA: true }
          - { PHP_VERSION: php71-fpm, MAGENTO_VERSION: 2.1.18, SAMPLE_DATA: false }
          - { PHP_VERSION: php71-fpm, MAGENTO_VERSION: 2.1.18, SAMPLE_DATA: true }
          - { PHP_VERSION: php7-fpm, MAGENTO_VERSION: 2.2.0, SAMPLE_DATA: false }
          - { PHP_VERSION: php7-fpm, MAGENTO_VERSION: 2.2.0, SAMPLE_DATA: true }
          - { PHP_VERSION: php71-fpm, MAGENTO_VERSION: 2.2.0, SAMPLE_DATA: false }
          - { PHP_VERSION: php71-fpm, MAGENTO_VERSION: 2.2.0, SAMPLE_DATA: true }
          - { PHP_VERSION: php7-fpm, MAGENTO_VERSION: 2.2.1, SAMPLE_DATA: false }
          - { PHP_VERSION: php7-fpm, MAGENTO_VERSION: 2.2.1, SAMPLE_DATA: true }
          - { PHP_VERSION: php71-fpm, MAGENTO_VERSION: 2.2.1, SAMPLE_DATA: false }
          - { PHP_VERSION: php71-fpm, MAGENTO_VERSION: 2.2.1, SAMPLE_DATA: true }
          - { PHP_VERSION: php7-fpm, MAGENTO_VERSION: 2.2.2, SAMPLE_DATA: false }
          - { PHP_VERSION: php7-fpm, MAGENTO_VERSION: 2.2.2, SAMPLE_DATA: true }
          - { PHP_VERSION: php71-fpm, MAGENTO_VERSION: 2.2.2, SAMPLE_DATA: false }
          - { PHP_VERSION: php71-fpm, MAGENTO_VERSION: 2.2.2, SAMPLE_DATA: true }
          - { PHP_VERSION: php7-fpm, MAGENTO_VERSION: 2.2.3, SAMPLE_DATA: false }
          - { PHP_VERSION: php7-fpm, MAGENTO_VERSION: 2.2.3, SAMPLE_DATA: true }
          - { PHP_VERSION: php71-fpm, MAGENTO_VERSION: 2.2.3, SAMPLE_DATA: false }
          - { PHP_VERSION: php71-fpm, MAGENTO_VERSION: 2.2.3, SAMPLE_DATA: true }
          - { PHP_VERSION: php7-fpm, MAGENTO_VERSION: 2.2.4, SAMPLE_DATA: false }
          - { PHP_VERSION: php7-fpm, MAGENTO_VERSION: 2.2.4, SAMPLE_DATA: true }
          - { PHP_VERSION: php71-fpm, MAGENTO_VERSION: 2.2.4, SAMPLE_DATA: false }
          - { PHP_VERSION: php71-fpm, MAGENTO_VERSION: 2.2.4, SAMPLE_DATA: true }
          - { PHP_VERSION: php7-fpm, MAGENTO_VERSION: 2.2.5, SAMPLE_DATA: false }
          - { PHP_VERSION: php7-fpm, MAGENTO_VERSION: 2.2.5, SAMPLE_DATA: true }
          - { PHP_VERSION: php71-fpm, MAGENTO_VERSION: 2.2.5, SAMPLE_DATA: false }
          - { PHP_VERSION: php71-fpm, MAGENTO_VERSION: 2.2.5, SAMPLE_DATA: true }
          - { PHP_VERSION: php7-fpm, MAGENTO_VERSION: 2.2.6, SAMPLE_DATA: false }
          - { PHP_VERSION: php7-fpm, MAGENTO_VERSION: 2.2.6, SAMPLE_DATA: true }
          - { PHP_VERSION: php71-fpm, MAGENTO_VERSION: 2.2.6, SAMPLE_DATA: false }
          - { PHP_VERSION: php71-fpm, MAGENTO_VERSION: 2.2.6, SAMPLE_DATA: true }
          - { PHP_VERSION: php7-fpm, MAGENTO_VERSION: 2.2.7, SAMPLE_DATA: false }
          - { PHP_VERSION: php7-fpm, MAGENTO_VERSION: 2.2.7, SAMPLE_DATA: true }
          - { PHP_VERSION: php71-fpm, MAGENTO_VERSION: 2.2.7, SAMPLE_DATA: false }
          - { PHP_VERSION: php71-fpm, MAGENTO_VERSION: 2.2.7, SAMPLE_DATA: true }
          - { PHP_VERSION: php7-fpm, MAGENTO_VERSION: 2.2.8, SAMPLE_DATA: false }
          - { PHP_VERSION: php7-fpm, MAGENTO_VERSION: 2.2.8, SAMPLE_DATA: true }
          - { PHP_VERSION: php71-fpm, MAGENTO_VERSION: 2.2.8, SAMPLE_DATA: false }
          - { PHP_VERSION: php71-fpm, MAGENTO_VERSION: 2.2.8, SAMPLE_DATA: true }
          - { PHP_VERSION: php7-fpm, MAGENTO_VERSION: 2.2.9, SAMPLE_DATA: false }
          - { PHP_VERSION: php7-fpm, MAGENTO_VERSION: 2.2.9, SAMPLE_DATA: true }
          - { PHP_VERSION: php71-fpm, MAGENTO_VERSION: 2.2.9, SAMPLE_DATA: false }
          - { PHP_VERSION: php71-fpm, MAGENTO_VERSION: 2.2.9, SAMPLE_DATA: true }
          - { PHP_VERSION: php7-fpm, MAGENTO_VERSION: 2.2.10, SAMPLE_DATA: false }
          - { PHP_VERSION: php7-fpm, MAGENTO_VERSION: 2.2.10, SAMPLE_DATA: true }
          - { PHP_VERSION: php71-fpm, MAGENTO_VERSION: 2.2.10, SAMPLE_DATA: false }
          - { PHP_VERSION: php71-fpm, MAGENTO_VERSION: 2.2.10, SAMPLE_DATA: true }
          - { PHP_VERSION: php7-fpm, MAGENTO_VERSION: 2.2.11, SAMPLE_DATA: false }
          - { PHP_VERSION: php7-fpm, MAGENTO_VERSION: 2.2.11, SAMPLE_DATA: true }
          - { PHP_VERSION: php71-fpm, MAGENTO_VERSION: 2.2.11, SAMPLE_DATA: false }
          - { PHP_VERSION: php71-fpm, MAGENTO_VERSION: 2.2.11, SAMPLE_DATA: true }
          - { PHP_VERSION: php71-fpm, MAGENTO_VERSION: 2.3.0, SAMPLE_DATA: false }
          - { PHP_VERSION: php71-fpm, MAGENTO_VERSION: 2.3.0, SAMPLE_DATA: true }
          - { PHP_VERSION: php72-fpm, MAGENTO_VERSION: 2.3.0, SAMPLE_DATA: false }
          - { PHP_VERSION: php72-fpm, MAGENTO_VERSION: 2.3.0, SAMPLE_DATA: true }
          - { PHP_VERSION: php71-fpm, MAGENTO_VERSION: 2.3.1, SAMPLE_DATA: false }
          - { PHP_VERSION: php71-fpm, MAGENTO_VERSION: 2.3.1, SAMPLE_DATA: true }
          - { PHP_VERSION: php72-fpm, MAGENTO_VERSION: 2.3.1, SAMPLE_DATA: false }
          - { PHP_VERSION: php72-fpm, MAGENTO_VERSION: 2.3.1, SAMPLE_DATA: true }
          - { PHP_VERSION: php71-fpm, MAGENTO_VERSION: 2.3.2, SAMPLE_DATA: false }
          - { PHP_VERSION: php71-fpm, MAGENTO_VERSION: 2.3.2, SAMPLE_DATA: true }
          - { PHP_VERSION: php72-fpm, MAGENTO_VERSION: 2.3.2, SAMPLE_DATA: false }
          - { PHP_VERSION: php72-fpm, MAGENTO_VERSION: 2.3.2, SAMPLE_DATA: true }
          - { PHP_VERSION: php71-fpm, MAGENTO_VERSION: 2.3.3, SAMPLE_DATA: false }
          - { PHP_VERSION: php71-fpm, MAGENTO_VERSION: 2.3.3, SAMPLE_DATA: true }
          - { PHP_VERSION: php72-fpm, MAGENTO_VERSION: 2.3.3, SAMPLE_DATA: false }
          - { PHP_VERSION: php72-fpm, MAGENTO_VERSION: 2.3.3, SAMPLE_DATA: true }
          - { PHP_VERSION: php73-fpm, MAGENTO_VERSION: 2.3.3, SAMPLE_DATA: false }
          - { PHP_VERSION: php73-fpm, MAGENTO_VERSION: 2.3.3, SAMPLE_DATA: true }
          - { PHP_VERSION: php71-fpm, MAGENTO_VERSION: 2.3.4, SAMPLE_DATA: false }
          - { PHP_VERSION: php71-fpm, MAGENTO_VERSION: 2.3.4, SAMPLE_DATA: true }
          - { PHP_VERSION: php72-fpm, MAGENTO_VERSION: 2.3.4, SAMPLE_DATA: false }
          - { PHP_VERSION: php72-fpm, MAGENTO_VERSION: 2.3.4, SAMPLE_DATA: true }
          - { PHP_VERSION: php73-fpm, MAGENTO_VERSION: 2.3.4, SAMPLE_DATA: false }
          - { PHP_VERSION: php73-fpm, MAGENTO_VERSION: 2.3.4, SAMPLE_DATA: true }
          - { PHP_VERSION: php71-fpm, MAGENTO_VERSION: 2.3.5-p1, SAMPLE_DATA: false }
          - { PHP_VERSION: php71-fpm, MAGENTO_VERSION: 2.3.5-p1, SAMPLE_DATA: true }
          - { PHP_VERSION: php72-fpm, MAGENTO_VERSION: 2.3.5-p1, SAMPLE_DATA: false }
          - { PHP_VERSION: php72-fpm, MAGENTO_VERSION: 2.3.5-p1, SAMPLE_DATA: true }
          - { PHP_VERSION: php73-fpm, MAGENTO_VERSION: 2.3.5-p1, SAMPLE_DATA: false }
          - { PHP_VERSION: php73-fpm, MAGENTO_VERSION: 2.3.5-p1, SAMPLE_DATA: true }
          - { PHP_VERSION: php71-fpm, MAGENTO_VERSION: 2.3.5-p2, SAMPLE_DATA: false }
          - { PHP_VERSION: php71-fpm, MAGENTO_VERSION: 2.3.5-p2, SAMPLE_DATA: true }
          - { PHP_VERSION: php72-fpm, MAGENTO_VERSION: 2.3.5-p2, SAMPLE_DATA: false }
          - { PHP_VERSION: php72-fpm, MAGENTO_VERSION: 2.3.5-p2, SAMPLE_DATA: true }
          - { PHP_VERSION: php73-fpm, MAGENTO_VERSION: 2.3.5-p2, SAMPLE_DATA: false }
          - { PHP_VERSION: php73-fpm, MAGENTO_VERSION: 2.3.5-p2, SAMPLE_DATA: true }
          - { PHP_VERSION: php71-fpm, MAGENTO_VERSION: 2.3.6, SAMPLE_DATA: false }
          - { PHP_VERSION: php71-fpm, MAGENTO_VERSION: 2.3.6, SAMPLE_DATA: true }
          - { PHP_VERSION: php72-fpm, MAGENTO_VERSION: 2.3.6, SAMPLE_DATA: false }
          - { PHP_VERSION: php72-fpm, MAGENTO_VERSION: 2.3.6, SAMPLE_DATA: true }
          - { PHP_VERSION: php73-fpm, MAGENTO_VERSION: 2.3.6, SAMPLE_DATA: false }
          - { PHP_VERSION: php73-fpm, MAGENTO_VERSION: 2.3.6, SAMPLE_DATA: true }
          - { PHP_VERSION: php71-fpm, MAGENTO_VERSION: 2.3.6-p1, SAMPLE_DATA: false }
          - { PHP_VERSION: php71-fpm, MAGENTO_VERSION: 2.3.6-p1, SAMPLE_DATA: true }
          - { PHP_VERSION: php72-fpm, MAGENTO_VERSION: 2.3.6-p1, SAMPLE_DATA: false }
          - { PHP_VERSION: php72-fpm, MAGENTO_VERSION: 2.3.6-p1, SAMPLE_DATA: true }
          - { PHP_VERSION: php73-fpm, MAGENTO_VERSION: 2.3.6-p1, SAMPLE_DATA: false }
          - { PHP_VERSION: php73-fpm, MAGENTO_VERSION: 2.3.6-p1, SAMPLE_DATA: true }
          - { PHP_VERSION: php73-fpm, MAGENTO_VERSION: 2.3.7, SAMPLE_DATA: false }
          - { PHP_VERSION: php73-fpm, MAGENTO_VERSION: 2.3.7, SAMPLE_DATA: true }
          - { PHP_VERSION: php74-fpm, MAGENTO_VERSION: 2.3.7, SAMPLE_DATA: false }
          - { PHP_VERSION: php74-fpm, MAGENTO_VERSION: 2.3.7, SAMPLE_DATA: true }
          - { PHP_VERSION: php73-fpm, MAGENTO_VERSION: 2.3.7-p1, SAMPLE_DATA: false }
          - { PHP_VERSION: php73-fpm, MAGENTO_VERSION: 2.3.7-p1, SAMPLE_DATA: true }
          - { PHP_VERSION: php74-fpm, MAGENTO_VERSION: 2.3.7-p1, SAMPLE_DATA: false }
          - { PHP_VERSION: php74-fpm, MAGENTO_VERSION: 2.3.7-p1, SAMPLE_DATA: true }
          - { PHP_VERSION: php73-fpm, MAGENTO_VERSION: 2.4.0, SAMPLE_DATA: false }
          - { PHP_VERSION: php73-fpm, MAGENTO_VERSION: 2.4.0, SAMPLE_DATA: true }
          - { PHP_VERSION: php74-fpm, MAGENTO_VERSION: 2.4.0, SAMPLE_DATA: false }
          - { PHP_VERSION: php74-fpm, MAGENTO_VERSION: 2.4.0, SAMPLE_DATA: true }
          - { PHP_VERSION: php73-fpm, MAGENTO_VERSION: 2.4.0-p1, SAMPLE_DATA: false }
          - { PHP_VERSION: php73-fpm, MAGENTO_VERSION: 2.4.0-p1, SAMPLE_DATA: true }
          - { PHP_VERSION: php74-fpm, MAGENTO_VERSION: 2.4.0-p1, SAMPLE_DATA: false }
          - { PHP_VERSION: php74-fpm, MAGENTO_VERSION: 2.4.0-p1, SAMPLE_DATA: true }
          - { PHP_VERSION: php73-fpm, MAGENTO_VERSION: 2.4.1, SAMPLE_DATA: false }
          - { PHP_VERSION: php73-fpm, MAGENTO_VERSION: 2.4.1, SAMPLE_DATA: true }
          - { PHP_VERSION: php74-fpm, MAGENTO_VERSION: 2.4.1, SAMPLE_DATA: false }
          - { PHP_VERSION: php74-fpm, MAGENTO_VERSION: 2.4.1, SAMPLE_DATA: true }
          - { PHP_VERSION: php73-fpm, MAGENTO_VERSION: 2.4.1-p1, SAMPLE_DATA: false }
          - { PHP_VERSION: php73-fpm, MAGENTO_VERSION: 2.4.1-p1, SAMPLE_DATA: true }
          - { PHP_VERSION: php74-fpm, MAGENTO_VERSION: 2.4.1-p1, SAMPLE_DATA: false }
          - { PHP_VERSION: php74-fpm, MAGENTO_VERSION: 2.4.1-p1, SAMPLE_DATA: true }
          - { PHP_VERSION: php73-fpm, MAGENTO_VERSION: 2.4.2, SAMPLE_DATA: false }
          - { PHP_VERSION: php73-fpm, MAGENTO_VERSION: 2.4.2, SAMPLE_DATA: true }
          - { PHP_VERSION: php74-fpm, MAGENTO_VERSION: 2.4.2, SAMPLE_DATA: false }
          - { PHP_VERSION: php74-fpm, MAGENTO_VERSION: 2.4.2, SAMPLE_DATA: true }
          - { PHP_VERSION: php73-fpm, MAGENTO_VERSION: 2.4.2-p1, SAMPLE_DATA: false }
          - { PHP_VERSION: php73-fpm, MAGENTO_VERSION: 2.4.2-p1, SAMPLE_DATA: true }
          - { PHP_VERSION: php74-fpm, MAGENTO_VERSION: 2.4.2-p1, SAMPLE_DATA: false }
          - { PHP_VERSION: php74-fpm, MAGENTO_VERSION: 2.4.2-p1, SAMPLE_DATA: true }
          - { PHP_VERSION: php73-fpm, MAGENTO_VERSION: 2.4.2-p2, SAMPLE_DATA: false }
          - { PHP_VERSION: php73-fpm, MAGENTO_VERSION: 2.4.2-p2, SAMPLE_DATA: true }
          - { PHP_VERSION: php74-fpm, MAGENTO_VERSION: 2.4.2-p2, SAMPLE_DATA: false }
          - { PHP_VERSION: php74-fpm, MAGENTO_VERSION: 2.4.2-p2, SAMPLE_DATA: true }
          - { PHP_VERSION: php73-fpm, MAGENTO_VERSION: 2.4.3, SAMPLE_DATA: false }
          - { PHP_VERSION: php73-fpm, MAGENTO_VERSION: 2.4.3, SAMPLE_DATA: true }
          - { PHP_VERSION: php74-fpm, MAGENTO_VERSION: 2.4.3, SAMPLE_DATA: false }
          - { PHP_VERSION: php74-fpm, MAGENTO_VERSION: 2.4.3, SAMPLE_DATA: true }
    steps:
    - uses: actions/checkout@v1

    - name: Build the Docker image (without sample data)
      if: matrix.cfg.SAMPLE_DATA == false
      run:
        docker build magento
        -t michielgerritsen/magento-project-community-edition:${{ matrix.cfg.PHP_VERSION }}-magento${{ matrix.cfg.MAGENTO_VERSION }}
        --build-arg MAGENTO_VERSION=${{ matrix.cfg.MAGENTO_VERSION }}
        --build-arg PHP_VERSION=${{ matrix.cfg.PHP_VERSION }}

    - name: Build the Docker image (with sample data)
      if: matrix.cfg.SAMPLE_DATA == true
      run:
        docker build magento
        -t michielgerritsen/magento-project-community-edition:${{ matrix.cfg.PHP_VERSION }}-magento${{ matrix.cfg.MAGENTO_VERSION }}-sample-data
        --build-arg MAGENTO_VERSION=${{ matrix.cfg.MAGENTO_VERSION }}
        --build-arg PHP_VERSION=${{ matrix.cfg.PHP_VERSION }}
        --build-arg SAMPLE_DATA=true

    - name: Docker hub login
      if: github.ref == 'refs/heads/build'
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push the image to Docker hub (without sample data)
      if: github.ref == 'refs/heads/build' && matrix.cfg.SAMPLE_DATA == false
      run: docker push michielgerritsen/magento-project-community-edition:${{ matrix.cfg.PHP_VERSION }}-magento${{ matrix.cfg.MAGENTO_VERSION }}

    - name: Push the image to Docker hub (with sample data)
      if: github.ref == 'refs/heads/build' && matrix.cfg.SAMPLE_DATA == true
      run: docker push michielgerritsen/magento-project-community-edition:${{ matrix.cfg.PHP_VERSION }}-magento${{ matrix.cfg.MAGENTO_VERSION }}-sample-data
